### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by gty3310** [gty3310/IdeasHunt#2]
- [x]  Users can sign up, sign in, log out
- [x]  Users can use a demo login to try the site
- [x]  Adequate styling
- [x]  Smooth, but-free navigation
- [x]  Users can't use certain features without logging in (creating posts & likes)

**Comment by gty3310** [comment]
https://ideashunt.herokuapp.com/#/

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
* I can signup a user with all completely new information but if I try to sign up with a different username but the same email, it fails but no error message is rendered - get an error in the console
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

Ti - address the unchecked items, and then I will close this issue.

**Comment by gty3310** [comment]
Hi Liz, for the point: Should not be able to visit /login or /signup, does that still apply for me since I use modal(which does not have a url for sign in)?

**Comment by gty3310** [comment]
also Liz, can I go check off those checkmarks myself?

**Comment by eshoule** [comment]
Ti, the /login, /signup still does apply to you, but is essentially the same as being able to visit a random route. You should not be able to visit any frontend routes that you don't have - so redirect to your splash or to an 404 error page. Let me know when you've fixed the errors, and I will check them off.

**Comment by gty3310** [comment]
@eshoule Thanks for letting me know! Also, I have finished those checkpoints. Please feel free to check them when you have time

**Comment by eshoule** [comment]
Ti- when I try to sign up with a different username, but the same email, there are errors in the console, and a blank page appears - this should work the same as trying to sign up with an existing username where the errors appear in the modal. Please fix this, and then I will close the issue.
